import { useRouter } from "next/router";
import type { GetServerSideProps } from "next";
import Head from "next/head";

// potential way to add header (to avoid api key in the url)
// https://refine.dev/blog/next-js-getinitialprops-and-getserversideprops/#automatic-caching-capabilities
export const getServerSideProps: GetServerSideProps = async (context) => {
  const stock = context.params.stockTicker;
  const apiKey = "cf7b9i2ad3iad4t5u5ugcf7b9i2ad3iad4t5u5v0";

  const res = await fetch(
    `https://finnhub.io/api/v1/search?q=${stock}&token=${apiKey}`
  );

  // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
  const data = await res.json();
  return {
    // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
    props: { data },
  };
};

const StockPage = ({ data }) => {
  const { stockTicker } = useRouter().query as {
    stockTicker: string;
  };

  console.log(data.result[0]);

  return (
    <>
      <Head>
        <title> {stockTicker} - FireStock</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="text-center">{stockTicker}</div>
        <div className="text-center">{data.result[0].description}</div>
      </main>
    </>
  );
};

export default StockPage;
