import { type NextPage } from "next";
import { useRouter } from "next/router";
import Head from "next/head";
import type { GetServerSideProps } from "next";

export const getServerSideProps: GetServerSideProps<{ data }> = async (
  context
) => {
  // Fetch data from external API
  const res = await fetch(
    `https://data.alpaca.markets/v2/stocks${stockTicker}`
  );
  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
};

const StockPage: NextPage = ({ data }) => {
  const { stockTicker } = useRouter().query as {
    stockTicker: string;
  };

  return (
    <>
      <Head>
        <title>`${stockTicker}` - FireStock</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container text-center">{data}</div>
      </main>
    </>
  );
};

export default StockPage;
